apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ default .Release.Name .Values.baseReleaseName }}
  namespace: {{.Values.namespace}}
  labels:
    release: {{ default .Release.Name .Values.baseReleaseName | quote }}
    app.kubernetes.io/name: {{ default .Values.serviceName .Values.applicationName | quote }}
    app.kubernetes.io/instance: {{ default .Release.Name .Values.baseReleaseName | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    prodhub.in/application: {{ default .Values.serviceName .Values.applicationName | quote }}
    prodhub.in/ephemeral-environment: {{ .Values.namespace | quote }}
    {{- if .Values.deploymentProfileName }}
    prodhub.in/deployment-profile: {{ .Values.deploymentProfileName | quote }}
    {{- end }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  replicas: {{ .Values.replicas | default 0 }}
  selector:
    matchLabels:
      release: {{ default .Release.Name .Values.baseReleaseName }}
  template:
    metadata:
      labels:
        release: {{ default .Release.Name .Values.baseReleaseName | quote }}
        app.kubernetes.io/name: {{ default .Values.serviceName .Values.applicationName | quote }}
        app.kubernetes.io/instance: {{ default .Release.Name .Values.baseReleaseName | quote }}
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        prodhub.in/application: {{ default .Values.serviceName .Values.applicationName | quote }}
        prodhub.in/ephemeral-environment: {{ .Values.namespace | quote }}
        {{- if .Values.deploymentProfileName }}
        prodhub.in/deployment-profile: {{ .Values.deploymentProfileName | quote }}
        {{- end }}
    spec:
      terminationGracePeriodSeconds: 60
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: {{ default .Release.Name .Values.baseReleaseName }}-dockerregistry
      {{- if eq .Values.isNodeSelectorEnabled "enabled" }}
      tolerations:
      - effect: NoSchedule
        key: app
        operator: Equal
        value: {{.Values.nodeSelectorApp}}
      nodeSelector:
        app: {{.Values.nodeSelectorApp}}
      {{- end}}
      containers:
      - image: {{.Values.registryURL}}/{{.Values.imageTag}}
        name: {{ .Values.serviceName | default (default .Release.Name .Values.baseReleaseName) }}
        command: [{{.Values.startUpCommand}}] 
        ports:
        - containerPort: {{.Values.ports}}
        {{- if eq .Values.isGRPCPortEnabled "enabled"}}
        - containerPort: {{.Values.grpcPort}}
        {{- end}}
        env:
        - name: APP
          value: {{.Values.serviceName}}
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: PORT
          value: "{{.Values.ports}}"
        - name: SERVER_PORT
          value: "{{.Values.ports}}"
        - name: ENV
          value: {{.Values.env}}
        resources:
          requests:
            cpu: {{.Values.cpuRequest}}
            memory: {{.Values.memoryRequest}}
            ephemeral-storage: {{.Values.ephemeralStorageRequest}}
          limits:
            cpu: {{.Values.cpuLimit}}
            memory: {{.Values.memoryLimit}}
            ephemeral-storage: {{.Values.ephemeralStorageLimit}}
      {{- if eq .Values.isSharedMemoryEnabled "enabled"}}
      volumes:
        - name: sharedmemory-{{.Values.serviceName}}
          emptyDir:
            medium: Memory
            sizeLimit: {{.Values.sharedMemoryLimit}}
      {{- end}}
