apiVersion: v1
kind: Secret
metadata:
  name: {{ default .Release.Name .Values.baseReleaseName }}-dockerregistry
  namespace: {{ .Values.namespace }}
  labels:
    release: {{ default .Release.Name .Values.baseReleaseName }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.registrySecret }}
