apiVersion: v1
kind: LimitRange
metadata:
  name: {{.Release.Name}}-limitrange
  namepsace: {{.Values.namespace}}
spec:
  limits:
    - type: Container
      default:
        cpu: 1000m
        memory: 1Gi
        ephemeral-storage: 5Gi
      defaultRequest:
        cpu: 100m
        memory: 100Mi
        ephemeral-storage: 1Gi