apiVersion: v1
kind: Service
metadata:
  labels:
    release: {{.Release.Name}}
    type: k8s
  name: {{.Release.Name}}-k8s
  namespace: {{.Values.namespace}}
spec:
  selector:
    release: {{.Release.Name}}
  type: NodePort
  ports:
    {{- if eq .Values.isGRPCPortEnabled "enabled" }}
    - name: grpc
      port: 80
      targetPort: {{.Values.grpcPort}}
      nodePort: {{.Values.grpcPort}}
    - name: http
      port: 8080
      targetPort: {{.Values.ports}}
      nodePort: {{.Values.ports}}
    {{- else}}
    - name: http
      port: 80
      targetPort: {{.Values.ports}}
      nodePort: {{.Values.ports}}
    {{- end}}

