---
apiVersion: v1
kind: Service
metadata:
  labels:
    release: {{ default .Release.Name .Values.baseReleaseName }}
    type: k8s
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{.Release.Name}}
    meta.helm.sh/release-namespace: {{.Release.Namespace}}
  name: {{ default .Release.Name .Values.baseReleaseName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    release: {{ default .Release.Name .Values.baseReleaseName }}
  type: ClusterIP
  ports:
    {{- if eq .Values.isGRPCPortEnabled "enabled" }}
    - name: grpc
      port: 80
      protocol: TCP
      targetPort: {{.Values.grpcPort}}
    - name: http
      port: 8080
      protocol: TCP
      targetPort: {{.Values.ports}}
    {{- else}}
    - name: http
      port: 80
      protocol: TCP
      targetPort: {{.Values.ports}}
    {{- end}}

