{{- if .Values.ingressYaml }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Values.namespace }}
  {{- if .Values.ingressClassName }}
  ingressClassName: {{ .Values.ingressClassName }}
  {{- end }}
  {{- $annotations := .Values.ingressAnnotations }}
  {{- if and $annotations (kindIs "string" $annotations) }}
    {{- $annotations = fromJson $annotations }}
  {{- end }}
  {{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
spec:
  rules:
    {{- .Values.ingressYaml | nindent 4 }}
{{- end }}