namespace: ""
baseReleaseName: ""

replicaCount: 1
pullPolicy: IfNotPresent

imagePullSecrets:
  - name: dockerhub

coredns:
  image:
    repository: harry2654/prodhub
    tag: environmentorchestrator-corednsproduction-6646354-04303aa
  service:
    type: ClusterIP
    port: 53

haproxy:
  image:
    repository: harry2654/prodhub
    tag: environmentorchestrator-haproxyproduction-1337173-04303aa
  service:
    type: ClusterIP
    port: 80
    targetPort: 80

listener:
  image:
    repository: harry2654/prodhub
    tag: environmentorchestrator-listenerproduction-6515072-04303aa

config:
  serviceDomain: "pod.local"
  resyncInterval: "30s"
  syncTimeout: "5s"

serviceAccount:
  create: true
  name: ""

resources: {}

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

nodeSelector: {}
tolerations: []
affinity: {}
