namespace: ""
serviceName: ""
applicationName: ""
baseReleaseName: ""
httpPort: ""
aiWorkspaceImage: ""
aiWorkspaceProdhubURL: ""
aiWorkspaceUserID: ""
aiWorkspaceToken: ""
aiWorkspacePreviewUrl: ""
imagePullPolicy: Always
replicas: 1
cpuRequest: 250m
cpuLimit: 1000m
memoryRequest: 256Mi
memoryLimit: 2Gi
ephemeralStorageRequest: 1Gi
ephemeralStorageLimit: 4Gi
