namespace: ""
serviceName: ""
applicationName: ""
baseReleaseName: ""
httpPort: ""
aiWorkspaceImage: "dockerhub.prodhub.in/prodhub-ai-workspace:aiworkspace-1.0.0"
aiWorkspaceProdhubURL: ""
aiWorkspaceUserID: ""
aiWorkspaceToken: ""
aiWorkspacePreviewUrl: ""
imagePullPolicy: Always
replicas: 1
cpuRequest: 250m
cpuLimit: 1000m
memoryRequest: 256Mi
memoryLimit: 1Gi
ephemeralStorageRequest: 1Gi
ephemeralStorageLimit: 2Gi
