apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ default .Release.Name .Values.baseReleaseName }}
  namespace: {{.Values.namespace}}
  annotations:
    helm.sh/resource-policy: keep
spec:
  replicas: {{ .Values.replicas | default 0 }}
  selector:
    matchLabels:
      release: {{ default .Release.Name .Values.baseReleaseName }}
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: {{.Values.maxSurgePercentage}}%
    type: RollingUpdate
  template:
    metadata:
      labels:
        release: {{ default .Release.Name .Values.baseReleaseName }}
      {{- if or (eq .Values.namespace "prodhub") (eq .Values.namespace "cicaptain") (eq .Values.namespace "cloudedgedeployer") (eq .Values.namespace "gateway") }}
      annotations:
        vault.hashicorp.com/role: prodhub-role
      {{- end }}
    spec:
      {{- if or (eq .Values.namespace "prodhub") (eq .Values.namespace "cicaptain") (eq .Values.namespace "cloudedgedeployer") (eq .Values.namespace "gateway") }}
      serviceAccountName: prodhub-sa
      {{- else if .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      {{- end }}
      terminationGracePeriodSeconds: 60
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: {{ default .Release.Name .Values.baseReleaseName }}-dockerregistry
      {{- if eq .Values.isNodeSelectorEnabled "enabled" }}
      tolerations:
      - effect: NoSchedule
        key: app
        operator: Equal
        value: {{.Values.nodeSelectorApp}}
      nodeSelector:
        app: {{.Values.nodeSelectorApp}}
      {{- end}}
      containers:
      - image: {{.Values.registryURL}}/{{.Values.image}}
        name: {{ .Values.serviceName | default (default .Release.Name .Values.baseReleaseName) }}
        command: [{{.Values.startUpCommand}}] 
        ports:
        - containerPort: {{.Values.ports}}
        {{- if eq .Values.isGRPCPortEnabled "enabled"}}
        - containerPort: {{.Values.grpcPort}}
        {{- end}}
        {{- if eq .Values.isStartupEnabled "enabled"}}
        startupProbe:
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 5
          failureThreshold: {{ mul .Values.serviceStartupTime 12 }}
          httpGet:
            path: {{.Values.startupProbePath}}
            port: {{.Values.startupProbePort}}
        {{- end}}
        readinessProbe:
          initialDelaySeconds: {{ .Values.readinessInitialDelay | default 45 }}
          successThreshold: {{ add (div .Values.serviceWarmupTime 5) 1 }}
          timeoutSeconds: 5
          periodSeconds: 5
          failureThreshold: 3
          httpGet:
            {{- if or (ne .Values.readinessAuthorization "na") (ne .Values.readinessContentType "na") (ne .Values.readinessAccept "na") }}
            httpHeaders:
              {{- if ne .Values.readinessAuthorization "na"}}
            - name: Authorization
              value: {{.Values.authorization}}
              {{- end}}
              {{- if ne .Values.readinessContentType "na"}}
            - name: Content-Type
              value: {{.Values.contentType}}
              {{- end}}
              {{- if ne .Values.readinessAccept "na"}}
            - name: accept
              value: {{.Values.readinessAccept}}
              {{- end}}
            {{- end}}
            path: {{.Values.readinessProbePath}}
            port: {{.Values.readinessPort}}
        livenessProbe:
          initialDelaySeconds: {{ .Values.livenessInitialDelay | default 90 }}
          successThreshold: {{ add (div .Values.serviceWarmupTime 5) 1 }}
          timeoutSeconds: 5
          periodSeconds: 5
          failureThreshold: 3
          httpGet:
            {{- if or (ne .Values.livenessAuthorization "na") (ne .Values.livenessContentType "na") (ne .Values.livenessAccept "na") }}
            httpHeaders:
              {{- if ne .Values.livenessAuthorization "na"}}
            - name: Authorization
              value: {{.Values.livenessAuthorization}}
              {{- end}}
              {{- if ne .Values.livenessContentType "na"}}
            - name: Content-Type
              value: {{.Values.livenessContentType}}
              {{- end}}
              {{- if ne .Values.livenessAccept "na"}}
            - name: accept
              value: {{.Values.livenessAccept}}
              {{- end}}
            {{- end}}
            path: {{.Values.livenessProbePath}}
            port: {{.Values.livenessPort}}
        env:
        - name: APP
          value: {{.Values.serviceName}}
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: PORT
          value: "{{.Values.ports}}"
        - name: SERVER_PORT
          value: "{{.Values.ports}}"
        - name: ENV
          value: {{.Values.env}}
        resources:
          requests:
            cpu: {{.Values.cpuRequest}}
            memory: {{.Values.memoryRequest}}
            ephemeral-storage: {{.Values.ephemeralStorageRequest}}
          limits:
            cpu: {{.Values.cpuLimit}}
            memory: {{.Values.memoryLimit}}
            ephemeral-storage: {{.Values.ephemeralStorageLimit}}
        volumeMounts:
        - name: {{ default .Release.Name .Values.baseReleaseName }}-configs
          mountPath: /tmp/configs
      volumes:
        {{- if eq .Values.isSharedMemoryEnabled "enabled"}}
        - name: sharedmemory-{{.Values.serviceName}}
          emptyDir:
            medium: Memory
            sizeLimit: {{.Values.sharedMemoryLimit}}
        {{- end}}
        - name: {{ default .Release.Name .Values.baseReleaseName }}-configs
          configMap:
            name: {{ default .Release.Name .Values.baseReleaseName }}-configs
            defaultMode: 0777
            items:
{{- with .Values.configItems}}
{{ toYaml . | indent 14}}
{{- end}}