{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
{{- $releaseName := default .Release.Name .Values.baseReleaseName -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-workspace" $releaseName | trunc 63 | trimSuffix "-" }}
  namespace: {{ required "namespace is required" .Values.namespace }}
  labels:
    release: {{ $releaseName | quote }}
    app.kubernetes.io/name: {{ required "applicationName is required" .Values.applicationName | quote }}
    prodhub.in/application: {{ required "applicationName is required" .Values.applicationName | quote }}
    prodhub.in/ephemeral-environment: {{ .Values.namespace | quote }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ required "persistence.size is required when persistence is enabled" .Values.persistence.size | quote }}
  {{- with .Values.persistence.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
