apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Release.Name}}-sa
  namespace: {{.Values.namespace}}
  annotations:
    {{- if eq .Values.namespace "prodhub" }}
    iam.gke.io/gcp-service-account: vault-client-gsa@prodhub-493713.iam.gserviceaccount.com
    {{- end }}
    {{- if .Values.annotations }}
    {{- toYaml .Values.annotations | nindent 4 }}
    {{- end }}