apiVersion: v1
kind: ServiceAccount
metadata:
  name: prodhub-sa
  namespace: {{ .Values.namespace }}
  annotations:
    vault.hashicorp.com/role: prodhub-role
    {{- if .Values.annotations }}
    {{- toYaml .Values.annotations | nindent 4 }}
    {{- end }}
