apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: environment-orchestrator-{{ default .Values.namespace .Values.ephemeralEnvironmentName }}
  namespace: {{ .Values.namespace }}
  labels:
    release: environment-orchestrator-{{ default .Values.namespace .Values.ephemeralEnvironmentName }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: "*.{{ default .Values.namespace .Values.ephemeralEnvironmentName }}.init.prodhub.in"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: environment-orchestrator-{{ default .Values.namespace .Values.ephemeralEnvironmentName }}-proxy
                port:
                  number: 80