{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: environment-orchestrator-{{ default .Values.namespace .Values.ephemeralEnvironmentName }}
  namespace: {{ .Values.namespace }}
  labels:
    release: environment-orchestrator-{{ default .Values.namespace .Values.ephemeralEnvironmentName }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: environment-orchestrator-{{ default .Values.namespace .Values.ephemeralEnvironmentName }}
  namespace: {{ .Values.namespace }}
  labels:
    release: environment-orchestrator-{{ default .Values.namespace .Values.ephemeralEnvironmentName }}
spec:
  rules:
    - apiGroups: [""]
      resources: ["pods"]
      verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: environment-orchestrator-{{ default .Values.namespace .Values.ephemeralEnvironmentName }}
  namespace: {{ .Values.namespace }}
  labels:
    release: environment-orchestrator-{{ default .Values.namespace .Values.ephemeralEnvironmentName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: environment-orchestrator-{{ default .Values.namespace .Values.ephemeralEnvironmentName }}
subjects:
  - kind: ServiceAccount
    name: environment-orchestrator-{{ default .Values.namespace .Values.ephemeralEnvironmentName }}
    namespace: {{ .Values.namespace }}
