apiVersion: v1
kind: Service
metadata:
  name: environment-orchestrator-{{ default .Values.namespace .Values.ephemeralEnvironmentName }}-dns
  namespace: {{ .Values.namespace }}
  labels:
    release: environment-orchestrator-{{ default .Values.namespace .Values.ephemeralEnvironmentName }}
spec:
  type: {{ .Values.coredns.service.type }}
  ports:
    - port: {{ .Values.coredns.service.port }}
      targetPort: 53
      protocol: {{ .Values.coredns.service.protocol }}
      name: dns
  selector:
    release: environment-orchestrator-{{ default .Values.namespace .Values.ephemeralEnvironmentName }}
---
apiVersion: v1
kind: Service
metadata:
  name: environment-orchestrator-{{ default .Values.namespace .Values.ephemeralEnvironmentName }}-proxy
  namespace: {{ .Values.namespace }}
  labels:
    release: environment-orchestrator-{{ default .Values.namespace .Values.ephemeralEnvironmentName }}
spec:
  type: {{ .Values.haproxy.service.type }}
  ports:
    - port: {{ .Values.haproxy.service.port }}
      targetPort: 80
      protocol: TCP
      name: proxy
  selector:
    release: environment-orchestrator-{{ default .Values.namespace .Values.ephemeralEnvironmentName }}
