environmentOrchestratorDns:
  enabled: false
  nameserver: ""
  searches:
    - svc.cluster.local
    - cluster.local
  options:
    - name: ndots
      value: "2"
aiWorkspaceCpuRequest: 250m
aiWorkspaceCpuLimit: 1000m
aiWorkspaceMemoryRequest: 256Mi
aiWorkspaceMemoryLimit: 4Gi
aiWorkspaceEphemeralStorageRequest: 1Gi
aiWorkspaceEphemeralStorageLimit: 4Gi
